const {default: fontAscii} = require('font-ascii')

const fonts = [
    ['Acrobatic', 185],
    // ['Alpha'],
    ['Avatar', 73],
    ['Big', 110],
    ['BigMoneyne', 125],
    ['BigMoneynw', 125],
    ['BigMoneyse', 125],
    ['BigMoneysw', 125],
    // ['Blocks', 240],
    ['Bulbhead', 80],
    // ['Cards', 100],
    ['Chiseled', 160],
    ['Crawford2', 87],
    ['Crazy', 175],
    ['DancingFont', 125],
    ['Diagonal3d', 170],
    // ['Doh'],
    ['Doom', 85],
    // ['EftiWall'],
    ['Epic', 110],
    // // ['Firefontk'],
    ['FireFonts', 100],
    ['FlowerPower', 155],
    ['FunFace', 125],
    ['FunFaces', 125],
    ['Ghost', 140],
    ['Graceful', 72],
    // ['Graffiti', 130],
    ['Impossible', 211],
    ['Isometric1', 165],
    ['Isometric2', 170],
    ['Isometric3', 170],
    ['Isometric4', 165],
    ['JSBracketLetters', 85],
    ['LilDevil', 130],
    ['Merlin1', 150],
    // ['Modular', 110],
    ['Ogre', 80],
    ['PatorjkCheese', 185],
    ['PatorjkHeX', 230],
    ['Rectangles', 85],
    // ['Slant', 105],
    // ['SlantRelief'],
    ['Small', 85],
    ['SmallIsometric1', 120],
    ['SmallSlant', 85],
    ['Soft', 117],
    ['Standard', 100],
    ['StarWars', 135],
    ['SubZero', 135],
    ['SwampLand', 160],
    ['Sweet', 125],
    ['Train', 110],
    ['Twisted', 135],
    ['Varsity', 150],
    ['WetLetts', 110],
]

for (const [font, minSize] of fonts) {
    // if (!minSize) {
        console.log('')
        console.log(`${font}:`)
        fontAscii('puzzle games', {typeface: font})
    // }
}
