export default [
    { name: 'Impossible', minWidth: 211 },
    { name: 'SubZero', minWidth: 135 },
    { name: 'FireFonts', minWidth: 100 },
    { name: 'Small', minWidth: 85 },
    { name: 'Avatar', minWidth: 73 },

    { name: 'Acrobatic', minWidth: 185 },
    // {name: 'Alpha'},
    { name: 'Avatar', minWidth: 73 },
    { name: 'Big', minWidth: 110 },
    { name: 'BigMoneyne', minWidth: 125 },
    { name: 'BigMoneynw', minWidth: 125 },
    { name: 'BigMoneyse', minWidth: 125 },
    { name: 'BigMoneysw', minWidth: 125 },
    // {name: 'Blocks', minWidth: 240},
    { name: 'Bulbhead', minWidth: 80 },
    // {name: 'Cards', minWidth: 100},
    { name: 'Chiseled', minWidth: 160 },
    { name: 'Crawford2', minWidth: 87 },
    { name: 'Crazy', minWidth: 175 },
    { name: 'DancingFont', minWidth: 125 },
    { name: 'Diagonal3d', minWidth: 170 },
    // {name: 'Doh'},
    { name: 'Doom', minWidth: 85 },
    // {name: 'EftiWall'},
    { name: 'Epic', minWidth: 110 },
    // // {name: 'Firefontk'},
    { name: 'FireFonts', minWidth: 100 },
    { name: 'FlowerPower', minWidth: 155 },
    { name: 'FunFace', minWidth: 125 },
    { name: 'FunFaces', minWidth: 125 },
    { name: 'Ghost', minWidth: 140 },
    { name: 'Graceful', minWidth: 72 },
    // {name: 'Graffiti', minWidth: 130},
    { name: 'Impossible', minWidth: 211 },
    { name: 'Isometric1', minWidth: 165 },
    { name: 'Isometric2', minWidth: 170 },
    { name: 'Isometric3', minWidth: 170 },
    { name: 'Isometric4', minWidth: 165 },
    { name: 'JSBracketLetters', minWidth: 85 },
    { name: 'LilDevil', minWidth: 130 },
    { name: 'Merlin1', minWidth: 150 },
    // {name: 'Modular', minWidth: 110},
    { name: 'Ogre', minWidth: 80 },
    { name: 'PatorjkCheese', minWidth: 185 },
    { name: 'PatorjkHeX', minWidth: 230 },
    { name: 'Rectangles', minWidth: 85 },
    // {name: 'Slant', minWidth: 105},
    // {name: 'SlantRelief'},
    { name: 'Small', minWidth: 85 },
    { name: 'SmallIsometric1', minWidth: 120 },
    { name: 'SmallSlant', minWidth: 85 },
    { name: 'Soft', minWidth: 117 },
    { name: 'Standard', minWidth: 100 },
    { name: 'StarWars', minWidth: 135 },
    { name: 'SubZero', minWidth: 135 },
    { name: 'SwampLand', minWidth: 160 },
    { name: 'Sweet', minWidth: 125 },
    { name: 'Train', minWidth: 110 },
    { name: 'Twisted', minWidth: 135 },
    { name: 'Varsity', minWidth: 150 },
    { name: 'WetLetts', minWidth: 110 }
]
