// TypeScript definition for the package
declare module 'font-ascii' {

    enum FONT_NAME {
        Acrobatic = 'Acrobatic',
        Alpha = 'Alpha',
        Avatar = 'Avatar',
        Big = 'Big',
        BigMoneyne = 'BigMoneyne',
        BigMoneynw = 'BigMoneynw',
        BigMoneyse = 'BigMoneyse',
        BigMoneysw = 'BigMoneysw',
        Blocks = 'Blocks',
        Bulbhead = 'Bulbhead',
        Cards = 'Cards',
        Chiseled = 'Chiseled',
        Crawford2 = 'Crawford2',
        Crazy = 'Crazy',
        DancingFont = 'DancingFont',
        Diagonal3d = 'Diagonal3d',
        Doh = 'Doh',
        Doom = 'Doom',
        EftiWall = 'EftiWall',
        Epic = 'Epic',
        Firefontk = 'Firefontk',
        FireFonts = 'FireFonts',
        FlowerPower = 'FlowerPower',
        FunFace = 'FunFace',
        FunFaces = 'FunFaces',
        Ghost = 'Ghost',
        Graceful = 'Graceful',
        Graffiti = 'Graffiti',
        Impossible = 'Impossible',
        Isometric1 = 'Isometric1',
        Isometric2 = 'Isometric2',
        Isometric3 = 'Isometric3',
        Isometric4 = 'Isometric4',
        JSBracketLetters = 'JSBracketLetters',
        LilDevil = 'LilDevil',
        Merlin1 = 'Merlin1',
        Modular = 'Modular',
        Ogre = 'Ogre',
        PatorjkCheese = 'PatorjkCheese',
        PatorjkHeX = 'PatorjkHeX',
        Rectangles = 'Rectangles',
        Slant = 'Slant',
        SlantRelief = 'SlantRelief',
        Small = 'Small',
        SmallIsometric1 = 'SmallIsometric1',
        SmallSlant = 'SmallSlant',
        Soft = 'Soft',
        Standard = 'Standard',
        StarWars = 'StarWars',
        SubZero = 'SubZero',
        SwampLand = 'SwampLand',
        Sweet = 'Sweet',
        Train = 'Train',
        Twisted = 'Twisted',
        Varsity = 'Varsity',
        WetLetts = 'WetLetts'
    }
    const f: (message: string, options?: {typeface: FONT_NAME | string}) => string

    export default f
}
